### ISSUE TITLE
Version of xmldom with critical security flaw is allowed

### ISSUE THREAD

**Issue by enquora** [mrcarlberg/objj-runtime#7]
The node branch depends on [xmldom](https://www.npmjs.com/package/@xmldom/xmldom) version >-[ 0.7.5](https://github.com/cappuccino/cappuccino/blob/511ce4b07d559d2137c7c35c529d625f45a422ad/package-lock.json#L123)
This is outdated and all versions earlier than 0.7.7 are flagged during npm update as creating [a critical security risk](https://www.npmjs.com/package/@xmldom/xmldom).

Latest version is is 0.8.6.

Note: this is for the published Objective-J runtime npm package rather than Cappuccino itself.

**Comment by mrcarlberg** [comment]
This is fixed with commit 7a5c5c704162f52df6f06d0a6b58b18d936d5a72
